version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: docker/auth.Dockerfile
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      - CONFIG_FILE=/app/configs/config.yaml
    volumes:
      - ./configs:/app/configs

  forum-service:
    build:
      context: .
      dockerfile: docker/forum.Dockerfile
    ports:
      - "8082:8082"
      - "9092:9092"
    depends_on:
      - postgres
      - auth-service
    environment:
      - CONFIG_FILE=/app/configs/config.yaml
    volumes:
      - ./configs:/app/configs

volumes:
  postgres_data: 